print('Welcome to the Mad Lib generator!')

adjective1 = raw_input('Please type an adjective: ')
adjective2 = raw_input('Please type another adjective: ')
adjective3 = raw_input('And another: ')
adjective4 = raw_input('And one more: ')
musician_name = raw_input('Please type in the first name of a woman musician: ')
plural_animal = raw_input('Please type a plural animal: ')
beverage = raw_input('Please type a beverage: ')
plural_noun = raw_input('Please type a plural noun: ')
verb = raw_input('Please type a verb: ')
plural_body_part = raw_input('Please type a plural body part: ')

print('')
print("Excellent choices. Here is your story...")
print('----------------------------------------')

print('There once was a ' + adjective1 + ' programmer named ' + musician_name)
print('who wanted to build a ' + adjective2 + ' mobile app to')
print('help ' + adjective3 + ' ' + plural_animal + ' find new homes.')
print(musician_name + ' stayed up all night, drinking lots of')
print ('caffeinated ' + beverage + ' as she worked and worked')
print('trying to complete her ' + adjective4 + ' program.')
print('Whenever ' + musician_name + ' hit a dead end, she would')
print('exclaim *' + plural_noun + '*!')
print('But she was not discouraged, and after a quick break')
print('to ' + verb + ' and clear her head, she got back to work.')
print('By morning, when the sun started to rise, she let out a')
print('big yawn and stretched her ' + plural_body_part + '.' ' Finally, she was done.')
